version: '3.8'

services:
  storybook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storybook
    image: mikaalaoutinen/desdeo-components
    ports:
      - 6006:6006
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app