version: '3.8'

services:
  storybook:
    build: .
    container_name: storybook
    image: desdeo-components-storybook
    ports:
      - 6006:6006
    volumes:
      - /app/node_modules
    working_dir: /app