# Workflow that is run when a pull request is merged to master branch.
#
# Includes the following steps:
#   1) Builds the application.
#
# Potential workflows:
# - Do npm patch release, unless commit message contains #skip-publish.
# - Generate a report of outdated dependencies.

name: Master branch workflow

on:
  push:
    branches:
     - master

jobs:
  build:
    name: Builds the application
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code from repository
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run build --if-present
      env:
        CI: true
